services:
  api1: &api
    image: rmoraes4/rinha-fraud2-2026:latest
    build: .
    environment:
      - PORT=8000
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  api2:
    <<: *api
    build: !reset null

  lb:
    image: nginx:alpine
    restart: always
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30M"
