events {
    worker_connections 65535;
}

http {
    access_log off;
    error_log /dev/null crit;
    
    keepalive_timeout 65;
    keepalive_requests 100;

    upstream api {
        server api1:8000 max_fails=1 fail_timeout=1s;
        server api2:8000 max_fails=1 fail_timeout=1s;
        keepalive 32;
    }

    server {
        listen 9999;
        
        location / {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Connection "";
            proxy_connect_timeout 5s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }
}